<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>13.0</LangVersion>
    <RootNamespace>NetFrames.YoshiPiClient</RootNamespace>
    <AssemblyName>NetFrames.YoshiPiClient</AssemblyName>

    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization>

    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\img_logo.bmp" />
    <EmbeddedResource Include="Assets\img_sample.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\FieldStack\Source\FieldStack.Core\FieldStack.Core.csproj" />
    <ProjectReference Include="..\..\..\FieldStack\Source\FieldStack.Linux\FieldStack.Linux.csproj" />
    <ProjectReference Include="..\..\..\FieldStack\Source\Drivers\Displays.TftSpi\Driver\Displays.TftSpi.csproj" />
    <ProjectReference Include="..\..\..\FieldStack\Source\Frameworks\Graphics.MicroLayout\Driver\Graphics.MicroLayout.csproj" />
    <ProjectReference Include="..\..\..\FieldStack\Source\Drivers\ICs.IOExpanders.Mcp23xxx\Driver\ICs.IOExpanders.Mcp23xxx.csproj" />
  </ItemGroup>
</Project>
