name: Upload/Publish MPAK

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build + Upload
      uses: WildernessLabs/meadow-cloud-package-upload@main
      with:
        project_path: "Source/NetFrames.EmbeddedClient/"
        organization_id: "d82f8ec7243a461581c2544070209fbd"
        api_key: ${{ secrets.API_KEY }}
        configs : '{
            "CONFIG_WIFI_SSID": "${{ secrets.CONFIG_WIFI_SSID }}", 
            "CONFIG_WIFI_PASS": "${{ secrets.CONFIG_WIFI_PASS }}", 
            "BASE_URL": "${{ secrets.BASE_URL }}"}'
        
    - name: Upload MPAK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: mpak-package
        path: Source/NetFrames.EmbeddedClient/bin/Release/*.mpak

    - name: Publish
      uses: WildernessLabs/meadow-cloud-package-publish@main
      with:
        api_key: ${{ secrets.API_KEY }}
        collection_id: "cb66c7ac57e14a85b5160f9b7c122203"